/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void readFileTest() {
        App classTest = new App();
        String path = "src/main/resources/allQuotes.json";
        assertNotNull("Should return a string", classTest.readFile(path));

    }

    @Test public void test_ronSwanson(){
        App test = new App();
        String exp = test.randomRonQuote();
        assertNotNull("There is something in here",exp);
    }

}
